version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn clean
      - mvn install
     #- mvn --batch-mode --update-snapshots verify 
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - 'target/teacher.core-0.0.1-SNAPSHOT.jar'
    - 'scripts/*.sh'
    - 'appspec.yml'
  #com/mycompany/app/HelloWorld.java, specifying yes will place this file in /HelloWorld.java
  discard-paths: yes